defaults:
  - task: adroit_multi

name: train_afro

task_name: ${task.name}
shape_meta: ${task.shape_meta} 
exp_name: "debug"

# horizon: 4
horizon: 33
n_obs_steps: 1
# n_action_steps: 3
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
keypoint_visible_rate: 1.0
obs_as_global_cond: True

policy:
  _target_: diffusion_policy_3d.policy.afro.AFRO
  use_point_crop: true
  condition_type: film
  use_down_condition: true
  use_mid_condition: true
  use_up_condition: true
  
  diffusion_step_embed_dim: 128
  down_dims:
  - 128
  - 256
  - 384
  crop_shape:
  - 80
  - 80
  encoder_output_dim: 64
  horizon: ${horizon} 
  kernel_size: 5
  n_action_steps: ${n_action_steps}
  n_groups: 8
  n_obs_steps: ${n_obs_steps}

  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    # num_train_timesteps: 1
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: sample

  generator_config: 
    time_schedule: {
      mode: 'linear',
      num_steps: 2000, 
      beta_start: 0.0001, 
      beta_end: 0.02,
    }
    interval_nums: 4
    cond_dims: 64
    mask_ratio: 0.0
    mask_type: 'rand'
    trans_dim: 384
    encoder_dims: 384
    depth: 12
    drop_path_rate: 0.1
    num_heads: 6
    group_size: 32
    num_group: 64

  npoints: 1024
  total_bs : 128
  step_per_update : 1

  num_inference_steps: 10
  obs_as_global_cond: true 
  shape_meta: ${shape_meta}

  use_pc_color: False
  pointnet_type: "pointnet"
  # pointnet_type: "pointnet_dynamicflow"
  # pointnet_type: "clip"
  # pointnet_type: "dinov2"
  # pointnet_type: "pointcnn"
  # pointnet_type: "uni3d"
  # pointnet_type: "pointdif"

  pointcloud_encoder_cfg:
    in_channels: 3
    out_channels: ${policy.encoder_output_dim}
    use_layernorm: true
    final_norm: layernorm # layernorm, none
    normal_channel: false

  idm_cfg:
    input_embed_dim: 64
    la_dim: 32
    net: {
      n_encoder_layers: 8,
      n_layers: 8,
      dim_model: 64,
      dim_feedforward: 512,
      n_heads: 8,
      dropout: 0.1,
      pre_norm: True,
      feedforward_activation: gelu,
      seq_len: 2,
      pos_enc: learned,
    }

ema:
  _target_: diffusion_policy_3d.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 192
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 192
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  # lr: 1.0e-4
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: true
  lr_scheduler: cosine
  # lr_warmup_steps: 500
  # num_epochs: 3000
  lr_warmup_steps: 5
  num_epochs: 301
  gradient_accumulate_every: 1
  use_ema: False
  rollout_every: 200
  checkpoint_every: 20
  val_every: 200
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  group: ${exp_name}
  id: null
  mode: online
  name: ${training.seed}
  project: dp3
  resume: true
  tags:
  - dp3

checkpoint:
  save_ckpt: False
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
